name: Summarise Upcoming Meetup Events

on:
  pull_request:
    types: [opened, synchronize, reopened ]
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1' # Monday at 7am GMT

jobs:
  summarise_events_with_llm:
    if: github.repository == 'Women-Coding-Community/WomenCodingCommunity.github.io' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/llm_meetup_summary/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/llm_meetup_summary/requirements.txt

      - name: Run summary script
        run: |
          cd tools/llm_meetup_summary
          python llm_event_summary.py --channel events
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_BOT_WEBHOOK: ${{ secrets.SLACK_BOT_WEBHOOK }}
